# Generated by Django 3.1.7 on 2021-02-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0002_delete_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
