# Generated by Django 3.1.7 on 2021-03-04 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0005_userprofile_image'),
        ('gamma', '0005_auto_20210302_1936'),
    ]

    operations = [
    ]
