# Generated by Django 3.1.7 on 2021-03-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0006_merge_20210304_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='measurement',
            field=models.TextField(choices=[('N/A', 'N/A'), ('km', 'km'), ('m', 'm')]),
        ),
    ]
