# Generated by Django 3.1.7 on 2021-03-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0010_post_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
