# Generated by Django 3.1.7 on 2021-03-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0011_userprofile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DurationField(),
        ),
    ]
