# Generated by Django 3.1.7 on 2021-03-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0012_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DurationField(default='0:00:00'),
        ),
    ]
