# Generated by Django 3.1.7 on 2021-03-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0014_auto_20210309_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DurationField(),
        ),
    ]
