# Generated by Django 3.1.7 on 2021-03-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0017_auto_20210310_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DurationField(),
        ),
    ]
