# Generated by Django 3.1.7 on 2021-03-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0019_userprofile_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tc',
            field=models.BooleanField(default=False),
        ),
    ]
