# Generated by Django 3.1.7 on 2021-03-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0020_auto_20210310_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default='whiteplaceholder.jpg', upload_to='images/'),
        ),
    ]
