# Generated by Django 3.1.7 on 2021-03-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0024_auto_20210310_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='points',
        ),
    ]
